### ISSUE TITLE
demo跟源码中看到的不一致

### ISSUE THREAD

**Issue by subying** [tm-fe/FlexTable#21]
**Describe the bug**
https://tm-fe.github.io/FlexTable/examples/dist/#/fixedLeft 这里面的demo已经跟源码中的对应不上，Age设置的『fixed: 'right'』并没有固定在右侧。

**To Reproduce**

**Expected behavior**
demo中Age固定在右侧。

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser: chrome 74.0.3729.169
 - Vue Version : 2.6.10
 - FlexTable Version : 0.0.8

**Comment by Robin-front** [comment]
fixed: 292c79da4667003118190d944de3cc73c1775a1b
