### ISSUE TITLE
column使用render时，该column的resize功能失效

### ISSUE THREAD

**Issue by subying** [tm-fe/FlexTable#9]
### Environment
mac os

### Version
flextable: 0.0.5
vue: 2.6.5

### Steps to reproduce
1. 设置 resizable 属性
2. columns 中某一列使用render
3. 对该列进行拖动调整宽度，发现没有作用

### What is expected?
无论column使用什么渲染方式都应该支持resize

**Comment by Robin-front** [comment]
columns 中的 key 是必填字段
